- name: Проверить наличие бинарника Node Exporter
  stat:
    path: "{{ node_exporter_bin_path }}"
  register: node_exporter_stat

- name: Установить факт установленности
  set_fact:
    node_exporter_installed: "{{ node_exporter_stat.stat.exists }}"

- name: Получить текущую версию node_exporter
  command: "{{ node_exporter_bin_path }} --version"
  register: node_exporter_version_cmd
  changed_when: false
  failed_when: false
  when: node_exporter_stat.stat.exists

- name: Извлечь номер версии из вывода
  set_fact:
    node_exporter_installed_version: "{{ node_exporter_version_cmd.stdout | regex_search('node_exporter, version ([0-9.]+)', '\\1') }}"
  when: node_exporter_version_cmd.stdout is defined

- name: Сравнить версии
  set_fact:
    node_exporter_needs_update: "{{ node_exporter_installed_version is version(node_exporter_version, '<') }}"
  when: node_exporter_installed_version is defined
