- name: Проверить, требуется ли обновление
  stat:
    path: "{{ node_exporter_bin_path }}"
  register: node_exporter_existing

- name: Удалить старый бинарник (если есть)
  file:
    path: "{{ node_exporter_bin_path }}"
    state: absent
  when: update_node_exporter or not node_exporter_existing.stat.exists

- name: Установить скачанный бинарник Node Exporter
  ansible.builtin.copy:
    src: "{{ node_exporter_tmp_bin }}"
    dest: "{{ node_exporter_bin_path }}"
    mode: '0755'
    remote_src: true
  when: not use_fallback_node_exporter and (update_node_exporter or not node_exporter_existing.stat.exists)

- name: Установить резервный бинарник Node Exporter
  ansible.builtin.copy:
    src: node_exporter_fallback
    dest: "{{ node_exporter_bin_path }}"
    mode: '0755'
  when: use_fallback_node_exporter and (update_node_exporter or not node_exporter_existing.stat.exists)
