- name: Загрузить переменные по ОС
  include_vars: "{{ ansible_os_family }}.yml"

- name: Определить окружение
  include_tasks: detect.yml

- name: Проверить установлен ли Node Exporter
  include_tasks: check_installed.yml

- name: Установка
  include_tasks: install.yml
  when: node_exporter_state == "present" and not node_exporter_installed

- name: Обновление
  include_tasks: update.yml
  when: node_exporter_state == "latest" and node_exporter_needs_update

- name: Удаление
  include_tasks: remove.yml
  when: node_exporter_state == "absent"

- name: Настройка systemd
  include_tasks: service.yml
  when: node_exporter_state != "absent"

- name: Проверка доступности
  include_tasks: check_health.yml
  when: node_exporter_healthcheck_enabled and node_exporter_state != "absent"
