- name: Проверка удаления Node Exporter
  include_tasks: remove.yml
  when: node_exporter_state == "absent"

- name: Скачивание бинарника Node Exporter
  include_tasks: download.yml
  when: node_exporter_state == "present"

- name: Установка Node Exporter
  include_tasks: install.yml
  when: node_exporter_state == "present"

- name: Развёртывание systemd unit
  include_tasks: systemd.yml
  when: node_exporter_state == "present"

- name: Проверка Node Exporter
  include_tasks: verify.yml
  when: node_exporter_state == "present"

- name: Очистка временных файлов
  include_tasks: cleanup.yml
  when: node_exporter_state == "present"
