- name: Остановить node_exporter
  systemd:
    name: node_exporter
    state: stopped
    enabled: false
    daemon_reload: true
  ignore_errors: true

- name: Удалить бинарник
  file:
    path: "{{ node_exporter_bin_path }}"
    state: absent

- name: Удалить systemd unit
  file:
    path: /etc/systemd/system/node_exporter.service
    state: absent

- name: Удалить пользователя
  user:
    name: "{{ node_exporter_user }}"
    state: absent
    remove: yes

- name: Удалить группу
  group:
    name: "{{ node_exporter_group }}"
    state: absent
