- name: Остановить node_exporter
  systemd:
    name: node_exporter
    state: stopped
    enabled: false
    daemon_reload: true
  ignore_errors: true

- name: Удалить бинарник
  file:
    path: "{{ node_exporter_bin_path }}"
    state: absent

- name: Удалить systemd unit
  file:
    path: "{{ node_exporter_unit_path }}"
    state: absent

- name: Очистить статус сервиса node_exporter
  command: systemctl reset-failed node_exporter.service
  ignore_errors: true
