- name: "Остановка и отключение службы node_exporter"
  systemd:
    name: node_exporter
    state: stopped
    enabled: no
    daemon_reload: yes
  ignore_errors: true

- name: "Удаление systemd unit-файла node_exporter"
  file:
    path: /etc/systemd/system/node_exporter.service
    state: absent

- name: "Удаление бинарника node_exporter"
  file:
    path: "{{ node_exporter_binary_path }}"
    state: absent
