- name: Остановить node_exporter
  systemd:
    name: node_exporter
    state: stopped
    daemon_reload: true
  ignore_errors: true
  notify: restart node_exporter

- name: Обновить Node Exporter бинарник
  get_url:
    url: "{{ node_exporter_download_url }}"
    dest: "{{ node_exporter_bin_path }}"
    mode: '0755'
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    force: true
