- name: Проверить, существует ли группа {{ group_item.name }}
  getent:
    database: group
    key: "{{ group_item.name }}"
  register: group_info
  failed_when: false
  changed_when: false

- name: Установить факт о существовании группы
  set_fact:
    group_exists: "{{ group_info is defined and group_info.name is defined }}"

- name: Установить текущий GID и участников
  set_fact:
    group_current_gid: "{{ group_info.gid | default(omit) }}"
    group_current_members: "{{ group_info.members | default([]) }}"
  when: group_exists

- name: Блокировка системной группы без разрешения
  fail:
    msg: >-
      Системная группа {{ group_item.name }} без group_allow_system_gid.
      Это приведёт к GID < 1000. Убери system: true или задай group_allow_system_gid: true.
  when:
    - group_item.system | default(false) | bool
    - group_item.gid is not defined
    - not (group_item.group_allow_system_gid | default(false))

- name: Проверка явно заданного GID < 1000 (если не разрешено)
  fail:
    msg: >-
      Безопасность: GID {{ group_item.gid }} < 1000 для {{ group_item.name }},
      это системный диапазон. Задай group_allow_system_gid: true, если уверен.
  when:
    - group_item.gid is defined
    - (group_item.gid | int) < 1000
    - not (group_item.group_allow_system_gid | default(false))

- name: Найти свободный GID при отсутствии заданного
  include_tasks: find_free_gid.yml
  when: group_item.gid is not defined

- name: Проверка GID-конфликта
  fail:
    msg: >-
      GID-конфликт: задан gid={{ group_item.gid }} для {{ group_item.name }},
      но он уже используется другой группой (gid {{ group_current_gid }}).
  when:
    - group_check_gid | default(true) | bool
    - group_item.gid is defined
    - group_exists
    - group_current_gid is defined
    - (group_item.gid | int) != (group_current_gid | int)

- name: Создать или обновить группу
  ansible.builtin.group:
    name: "{{ group_item.name }}"
    gid: "{{ group_item.gid | default(omit) }}"
    state: "{{ group_item.state }}"
    system: "{{ group_item.system | default(omit) }}"

- name: Лог создана/обновлена группа
  include_role:
    name: shared/log-events
  vars:
    log_event:
      source: manage-groups
      action: group-created
      group: "{{ group_item.name }}"
      gid: "{{ group_item.gid }}"
  when: group_log_enabled | default(true)
