- name: Проверка группы перед созданием
  include_tasks: check_group.yml

- name: Создать или обновить группу
  ansible.builtin.group:
    name: "{{ group_item.name }}"
    gid: >-
      {{
        group_item.gid
          if group_item.gid is defined else
        (
          group_gid_map[group_item.name]
            if group_gid_map is defined and group_gid_map[group_item.name] is defined
            else omit
        )
      }}
    state: "{{ group_item.state }}"
    system: "{{ group_item.system | default(omit) }}"

- name: Лог создана/обновлена группа
  include_role:
    name: shared/log-events
  vars:
    log_event:
      source: manage-groups
      action: group-created
      group: "{{ group_item.name }}"
      gid: "{{ group_item.gid }}"
  when: group_log_enabled | default(true)
