- name: Получить домашнюю директорию пользователя {{ user.name }}
  include_tasks: utils/detect_home_path.yml
  vars:
    username: "{{ user.name }}"

- name: Убедиться, что .ssh каталог существует
  file:
    path: "{{ user_home_path }}/.ssh"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0700'

- name: Прочитать публичный ключ (локально)
  delegate_to: localhost
  slurp:
    src: "{{ ssh_key_storage_path }}/{{ user.name }}/id_{{ user.ssh_key_type | default(ssh_key_type_default) }}.pub"
  register: pub_key_data

- name: Добавить публичный ключ через blockinfile
  blockinfile:
    path: "{{ user_home_path }}/.ssh/authorized_keys"
    create: yes
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0600'
    marker: "# {mark} managed-by manage-ssh"
    block: "{{ pub_key_data['content'] | b64decode }}"
