- name: Получить shell пользователя
  shell: "getent passwd {{ item.name }} | cut -d: -f7"
  register: user_shell
  changed_when: false
  failed_when: false

- name: Получить группы пользователя
  command: "id -nG {{ item.name }}"
  register: user_groups
  changed_when: false
  failed_when: false

- name: Получить список процессов пользователя
  shell: "pgrep -u {{ item.name }}"
  register: user_processes
  changed_when: false
  failed_when: false

- name: Проверка объёма домашней директории
  shell: "du -sh /home/{{ item.name }} 2>/dev/null || echo 'no home dir'"
  register: home_dir_size
  changed_when: false
  failed_when: false
