- name: Проверка существования пользователя {{ item.name }}
  getent:
    database: passwd
    key: "{{ item.name }}"
  register: user_check
  failed_when: false
  changed_when: false
  when: not users_dry_run | default(false)

- name: Проверка UID на конфликт
  shell: "getent passwd | awk -F: '{print $3}' | grep -q '^{{ item.uid }}$'"
  register: uid_check
  changed_when: false
  failed_when: false
  when: item.uid is defined and not users_dry_run | default(false)

- name: Отладка - UID уже используется
  debug:
    msg: "UID {{ item.uid }} уже используется. Пользователь {{ item.name }} не будет создан."
  when:
    - item.uid is defined
    - uid_check is defined
    - uid_check.rc is defined
    - uid_check.rc == 0
    - not users_dry_run | default(false)

- name: Логирование конфликта UID
  include_role:
    name: shared/log-events
  vars:
    log_action: "skipped"
    log_level: "WARNING"
    log_message: "UID {{ item.uid }} уже используется. Пользователь {{ item.name }} не создан."
  when:
    - item.uid is defined
    - uid_check is defined
    - uid_check.rc == 0
    - not users_dry_run | default(false)

- name: "Создание пользователя {{ item.name }}"
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid | default(omit) }}"
    gid: "{{ item.gid | default(omit) }}"
    shell: "{{ item.shell | default(default_shell) }}"
    groups: "{{ item.groups | default(omit) }}"
    comment: "{{ item.comment | default(omit) }}"
    create_home: true
    state: present
    append: true
  when:
    - not users_dry_run | default(false)
    - item.uid is not defined or uid_check.rc != 0

- name: "DRY-RUN: Эмуляция создания пользователя {{ item.name }}"
  debug:
    msg: "DRY-RUN: Создали бы пользователя {{ item.name }} с shell={{ item.shell }}, groups={{ item.groups }}"
  when: users_dry_run | default(false)

- name: "Логирование создания пользователя {{ item.name }}"
  include_role:
    name: shared/log-events
  vars:
    log_action: "created"
    log_level: "INFO"
    log_message: "User {{ item.name }} создан. Shell: {{ item.shell }} Groups: {{ item.groups | default('[]') }}"
  when:
    - not users_dry_run | default(false)
    - item.uid is not defined or uid_check.rc != 0
