- name: Проверка существования пользователя {{ item.name }}
  getent:
    database: passwd
    key: "{{ item.name }}"
  register: user_check
  failed_when: false
  changed_when: false

- name: Установить факт user_exists
  set_fact:
    user_exists: "{{ user_check.ansible_facts.getent_passwd[item.name] is defined }}"

- name: Пропустить — пользователь {{ item.name }} не найден
  debug:
    msg: "Пользователь {{ item.name }} не найден. Пропуск."
  when: not user_exists

- name: Удаление пользователя
  block:
    - name: Проверка защищённости пользователя
      include_tasks: check_sensitive_user.yml

    - name: Сбор информации
      include_tasks: collect_user_facts.yml

    - name: Удаление пользователя
      include_tasks: remove_user.yml

  when: user_exists

- name: "DRY-RUN: Удалили бы пользователя {{ item.name }}"
  debug:
    msg: |
      DRY-RUN: Удалили бы пользователя {{ item.name }}
      Shell: {{ user_shell.stdout | default('unknown') }}
      Groups: {{ user_groups.stdout | default('unknown') }}
      Home size: {{ home_dir_size.stdout | default('n/a') }}
      Active processes: {{ user_processes.stdout | default('none') }}
  when: users_dry_run | default(false)
