- name: Проверка защищённости пользователя
  include_tasks: check_sensitive_user.yml
  when: not users_dry_run | default(false)

- name: Сбор информации
  include_tasks: collect_user_facts.yml
  when: not users_dry_run | default(false)

- name: Удаление пользователя
  include_tasks: remove_user.yml
  when: not users_dry_run | default(false)

- name: "DRY-RUN: Удалили бы пользователя {{ item.name }}"
  debug:
    msg: |
      DRY-RUN: Удалили бы пользователя {{ item.name }}
      Shell: {{ user_shell.stdout | default('unknown') }}
      Groups: {{ user_groups.stdout | default('unknown') }}
      Home size: {{ home_dir_size.stdout | default('n/a') }}
      Active processes: {{ user_processes.stdout | default('none') }}
  when: users_dry_run | default(false)
