- name: Проверка активных процессов пользователя
  shell: "pgrep -u {{ item.name }}"
  register: user_processes_check
  changed_when: false
  failed_when: false

- name: Отказаться от удаления, если есть активные процессы
  fail:
    msg: "Нельзя удалить пользователя {{ item.name }}, пока у него есть активные процессы: {{ user_processes_check.stdout_lines }}"
  when: user_processes_check.stdout != ""

- name: Удалить пользователя {{ item.name }}
  user:
    name: "{{ item.name }}"
    state: absent
    remove: true

- name: Логирование удаления пользователя
  include_role:
    name: shared/log-events
  vars:
    log_action: "deleted"
    log_level: "WARNING"
    log_message: |
      User {{ item.name }} удалён.
      Shell: {{ user_shell.stdout | default('unknown') }}
      Groups: {{ user_groups.stdout | default('unknown') }}
      Home size: {{ home_dir_size.stdout | default('n/a') }}
      Active processes: {{ user_processes.stdout | default('none') }}
