- name: Проверка имени пользователя
  assert:
    that:
      - item.name is defined
      - item.name is string
      - item.name | length > 0

- name: Проверка shell
  assert:
    that:
      - item.shell is not defined or item.shell is string

- name: Проверка groups
  assert:
    that:
      - item.groups is not defined or item.groups is iterable

- name: Проверка UID
  assert:
    that:
      - item.uid is not defined or (item.uid is number and item.uid >= 1000)

- name: Проверка GID
  assert:
    that:
      - item.gid is not defined or (item.gid is number and item.gid >= 1000)
