- name: Проверка существования пользователя {{ item.name }}
  getent:
    database: passwd
    key: "{{ item.name }}"
  register: user_check
  failed_when: false
  changed_when: false
  when: not users_dry_run | default(false)

- name: Проверка UID на конфликт
  shell: "getent passwd | awk -F: '{print $3}' | grep -q '^{{ item.uid }}$'"
  register: uid_check
  changed_when: false
  failed_when: false
  when: item.uid is defined and not users_dry_run | default(false)

- name: Отладка - UID уже используется
  debug:
    msg: "UID {{ item.uid }} уже используется. Нужно выбрать другой или убрать вручную."
  when:
    - item.uid is defined
    - uid_check is defined
    - uid_check.rc is defined
    - uid_check.rc == 0
    - not users_dry_run | default(false)
