- name: Клонировать ВМ {{ item.item.name }} на ноде {{ item.item.target_node | default(proxmox_node) }}
  uri:
    url: "{{ proxmox_api_url }}/nodes/{{ item.item.target_node | default(proxmox_node) }}/qemu/{{ item.item.source_vmid | default(template_vmid) }}/clone"
    method: POST
    headers:
      Authorization: "PVEAPIToken={{ proxmox_user }}={{ proxmox_token }}"
    body_format: form-urlencoded
    body:
      newid: "{{ item.item.id }}"
      name: "{{ item.item.name }}"
      target: "{{ item.item.target_node | default(proxmox_node) }}"
      full: "{{ item.item.full | default(1) }}"
    validate_certs: no

