- name: Сформировать тело запроса cloud-init
  set_fact:
    cloud_init_payload:
      ciuser: "{{ item.ci_user | default(default_ci_user) }}"
      sshkeys: >-
        {{
          (item.ssh_key | default(default_ci_pubkey))
          | regex_replace('\n', ' ')
          | regex_replace('\\s+', ' ')
          | trim
        }}
      ipconfig0: "ip={{ item.ip }}/{{ item.cidr | default(24) }},gw={{ item.gw | default(default_gateway) }}"
