- name: Установить net0 (bridge) для {{ item.item.name }}
  uri:
    url: "{{ proxmox_api_url }}/nodes/{{ item.item.target_node | default(proxmox_node) }}/qemu/{{ item.item.id }}/config"
    method: POST
    headers:
      Authorization: "PVEAPIToken={{ proxmox_user }}={{ proxmox_token }}"
    body_format: form-urlencoded
    body:
      net0: "virtio,bridge={{ item.item.bridge | default('br-vlan2875') }}"
    validate_certs: no
  tags: [net0]
