- name: Установить net0 (bridge) и сетевую модель
  uri:
    url: "{{ proxmox_api_url }}/nodes/{{ item.item.target_node | default(proxmox_node) }}/qemu/{{ item.item.id }}/config"
    method: POST
    headers:
      Authorization: "PVEAPIToken={{ proxmox_user }}={{ proxmox_token }}"
    body_format: form-urlencoded
    body:
      net0: "{{ item.item.nic_model }},bridge={{ item.item.bridge }}"
    validate_certs: no
  when:
    - item.item.nic_model is defined
    - item.item.bridge is defined
  tags: [net0]
