- name: Создать снапшот для ВМ {{ item.name }}
  uri:
    url: "{{ proxmox_api_url }}/nodes/{{ item.target_node | default(proxmox_node) }}/qemu/{{ item.id }}/snapshot"
    method: POST
    headers:
      Authorization: "PVEAPIToken={{ proxmox_user }}={{ proxmox_token }}"
    body_format: form-urlencoded
    body:
      snapname: "{{ item.snapshot_name | default('auto-snapshot') }}"
      description: "Created by Ansible"
    validate_certs: no
  loop: "{{ vm_list }}"
  when: item.state == 'snapshot'
