- name: Остановить ВМ {{ item.item.name }} (мягко)
  uri:
    url: "{{ proxmox_api_url }}/nodes/{{ item.item.target_node }}/qemu/{{ item.item.id }}/status/stop"
    method: POST
    headers:
      Authorization: "PVEAPIToken={{ proxmox_user }}={{ proxmox_token }}"
    validate_certs: no
    status_code: [200, 400]
  ignore_errors: true
