- name: Установить .deb репозиторий для Debian-based
  ansible.builtin.apt:
    deb: "{{ item.list_url }}"
    update_cache: yes
  when:
    - ansible_os_family == "Debian"
    - item.enabled
    - item.for_os | lower == "debian"
    - item.list_url is defined
  environment:
    http_proxy: "http://{{ fix_repository_proxy_host }}:{{ fix_repository_proxy_port }}"
    https_proxy: "http://{{ fix_repository_proxy_host }}:{{ fix_repository_proxy_port }}"
  loop: "{{ fix_repository_external_repos }}"
  loop_control:
    label: "{{ item.name }}"
  ignore_errors: true

- name: Установить .rpm репозиторий для RedHat-based
  ansible.builtin.yum:
    name: "{{ item.repo_url }}"
    state: present
  when:
    - ansible_os_family == "RedHat"
    - item.enabled
    - item.for_os | lower == "redhat"
    - item.repo_url is defined
  environment:
    http_proxy: "http://{{ fix_repository_proxy_host }}:{{ fix_repository_proxy_port }}"
    https_proxy: "http://{{ fix_repository_proxy_host }}:{{ fix_repository_proxy_port }}"
  loop: "{{ fix_repository_external_repos }}"
  loop_control:
    label: "{{ item.name }}"
  ignore_errors: true
