- name: Установить флаг начала проверки
  set_fact:
    repo_check_started: true

- name: Проверить APT (apt update)
  when: ansible_os_family == "Debian"
  become: true
  block:
    - name: Выполнить apt update
      command: apt update
      register: apt_result
      changed_when: false
      failed_when: false

    - name: Установить флаг успешности
      set_fact:
        repo_check_successful: true
      when: apt_result.rc == 0

- name: Проверить YUM/DNF (dnf makecache)
  when: ansible_os_family == "RedHat"
  become: true
  block:
    - name: Выполнить dnf makecache
      command: dnf makecache
      register: yum_result
      changed_when: false
      failed_when: false

    - name: Установить флаг успешности
      set_fact:
        repo_check_successful: true
      when: yum_result.rc == 0

- name: Вывести статус проверки репозиториев
  debug:
    msg: "{{ ansible_pkg_mgr | upper }} update выполнен успешно. (Успешно: {{ repo_check_successful | default(false) }})"
