- name: Проверить, активна ли роль
  fail:
    msg: "Роль fix-repository отключена"
  when: not fix_repository_enabled

- name: Проверить репозитории (если не пропущено)
  include_tasks: check_existing_repos.yml
  when: not fix_repository_skip_check_existing

- name: Завершить, если всё уже работает
  meta: end_play
  when: repo_check_successful | default(false) and fix_repository_exit_on_success

- name: Создать бэкапы текущих конфигураций репозиториев
  include_tasks: backup_existing_repos.yml

- name: Установить внешние репозитории (если явно разрешено)
  include_tasks: add_external_repos.yml
  when:
    - fix_repository_enable_external_repos | default(false)
    - fix_repository_external_repos | length > 0

- name: Настроить Nexus
  include_tasks: configure_nexus_repos.yml
  when: fix_repository_type == "nexus"

- name: Настроить прокси
  include_tasks: configure_proxy_repos.yml
  when: fix_repository_type == "proxy"

- name: Финальная проверка состояния репозиториев
  include_tasks: final_repo_check.yml
