- name: Подключение файла с проверками
  ansible.builtin.include_tasks: validate.yml

- name: Подключение файла сканирования "ДО"
  ansible.builtin.include_tasks: scan_disks.yml

- name: "EXTEND | Запомнить разделы, которые уже есть на диске"
  become: true
  ansible.builtin.shell: "lsblk -lnpo NAME {{ item.disk_device }}"
  register: partitions_before
  changed_when: false

- name: "EXTEND | Создать новый раздел в свободном пространстве"
  become: true
  ansible.builtin.shell: "parted -s -- {{ item.disk_device }} mkpart primary 17.2GB 100%"
  changed_when: true

- name: "EXTEND | Заставить ядро перечитать таблицу разделов"
  become: true
  ansible.builtin.command: partprobe {{ item.disk_device }}
  changed_when: false

- name: "EXTEND | Получить список разделов ПОСЛЕ создания"
  become: true
  ansible.builtin.shell: "lsblk -lnpo NAME {{ item.disk_device }}"
  register: partitions_after
  changed_when: false

- name: "EXTEND | Вычислить и сохранить имя нового раздела в переменную"
  become: true
  ansible.builtin.set_fact:
    new_partition_device: "{{ (partitions_after.stdout_lines | difference(partitions_before.stdout_lines)) | first }}"

- name: "EXTEND | Вывести имя найденного раздела (для отладки)"
  ansible.builtin.debug:
    msg: "Обнаружен новый раздел для работы: {{ new_partition_device }}"
  when: new_partition_device is defined

- name: "EXTEND | Создать Physical Volume на НОВОМ разделе (pvcreate)"
  become: true
  ansible.builtin.shell: "yes | pvcreate -ff {{ new_partition_device }}"
  changed_when: true
  notify: Перезагрузить сервер (если требуется)

- name: "EXTEND | Расширить существующую Volume Group НОВЫМ разделом (vgextend)"
  become: true
  ansible.builtin.command: "vgextend {{ item.vg_to_extend }} {{ new_partition_device }}"
  changed_when: true
  notify: Перезагрузить сервер (если требуется)

- name: "EXTEND | Выполнить операции для каждого Logical Volume"
  ansible.builtin.include_tasks: extend_lv_item.yml
  loop: "{{ item.lvs_to_modify }}"
  loop_control:
    loop_var: lv_item

- name: Подключение файла сканирования "ПОСЛЕ"
  ansible.builtin.include_tasks: scan_disks.yml
