- name: "Создание точки монтирования '{{ mount_point }}'"
  become: true
  ansible.builtin.file:
    path: "{{ mount_point }}"
    state: directory
    mode: '0755'

- name: "Монтирование и запись в fstab"
  become: true
  ansible.builtin.mount:
    path: "{{ mount_point }}"
    src: "/dev/{{ vg_name }}/{{ lv_name }}"
    fstype: "{{ fs_type | default('ext4') }}"
    state: mounted
    opts: defaults
    dump: 0
    passno: 2
  notify: Перезагрузить сервер (по необходимости)

- name: "Настройка SELinux"
  ansible.builtin.include_tasks: handle_selinux.yml
  when: selinux_context is defined
