- name: "SELINUX | Установить заданный контекст для '{{ lv_item.mount_point }}'"
  become: true
  community.general.sefcontext:
    target: "{{ lv_item.mount_point }}(/.*)?" # <-- ИЗМЕНЕНО
    setype: "{{ lv_item.selinux_context }}"
    state: present
    reload: true
  when: lv_item.selinux_context is defined and ansible_selinux.status == 'enabled'
  notify: Перезагрузить сервер (если требуется)
