- name: "ПЕРЕЕЗД | Остановить сервис логирования"
  become: true
  ansible.builtin.service:
    name: rsyslog
    state: stopped

- name: "ПЕРЕЕЗД | Переместить старое содержимое в *.old"
  become: true
  ansible.builtin.command: "mv {{ lv_item.mount_point }} {{ lv_item.mount_point }}.old"
  changed_when: false

- name: "ПЕРЕЕЗД | Создать новую пустую директорию"
  become: true
  ansible.builtin.file: { path: "{{ lv_item.mount_point }}", state: directory, mode: '0755' }

- name: "ПЕРЕЕЗД | Смонтировать новый том"
  become: true
  ansible.builtin.mount:
    path: "{{ lv_item.mount_point }}"
    src: "/dev/{{ item.vg_name | default(item.vg_to_extend) }}/{{ lv_item.name }}"
    fstype: "{{ effective_fs_type }}"
    state: mounted
    opts: defaults
    dump: 0
    passno: 2
  notify: Перезагрузить сервер (если требуется)

- name: "ПЕРЕЕЗД | Скопировать старую структуру и файлы обратно"
  become: true
  ansible.builtin.command: "cp -aT {{ lv_item.mount_point }}.old/ {{ lv_item.mount_point }}/"
  changed_when: true

- name: "ПЕРЕЕЗД | Настройка SELinux"
  ansible.builtin.include_tasks: handle_selinux.yml

- name: "ПЕРЕЕЗД | Удалить временную директорию *.old"
  become: true
  ansible.builtin.file:
    path: "{{ lv_item.mount_point }}.old"
    state: absent

- name: "ПЕРЕЕЗД | Запустить сервис логирования обратно"
  become: true
  ansible.builtin.service:
    name: rsyslog
    state: started
