- name: "Определение типа ФС для '{{ lv_item.name }}' (если существует)"
  become: true
  ansible.builtin.shell: "blkid -s TYPE -o value /dev/{{ item.vg_to_extend }}/{{ lv_item.name }}"
  register: blkid_check
  failed_when: false
  changed_when: false

- name: "Вычисление итогового типа ФС для '{{ lv_item.name }}'"
  ansible.builtin.set_fact:
    effective_fs_type: "{{ lv_item.fs_type | default(blkid_check.stdout) }}"

- name: "Изменение/создание Logical Volume '{{ lv_item.name }}'"
  become: true
  community.general.lvol: { vg: "{{ item.vg_to_extend }}", lv: "{{ lv_item.name }}", size: "{{ lv_item.new_size }}", state: present }

- name: "Расширение/создание файловой системы для '{{ lv_item.name }}'"
  become: true
  community.general.filesystem:
    dev: "/dev/{{ item.vg_to_extend }}/{{ lv_item.name }}"
    fstype: "{{ effective_fs_type }}"
    resizefs: true
  when: effective_fs_type != ""
