- name: "MANAGE-DISKS | Установить необходимые утилиты"
  become: true
  ansible.builtin.package:
    name:
      - lvm2
      - xfsprogs
      - parted
      - cloud-utils-growpart
      - policycoreutils-python-utils
      - python3-libselinux
    state: present

- name: "Обработка дисковой конфигурации: {{ item.operation_type | default('create') }}"
  ansible.builtin.include_tasks: "{{ item.operation_type | default('create') }}_logic.yml"
  loop: "{{ disks }}"
  loop_control:
    loop_var: item
