- name: "Проверка входных данных и безопасности"
  include_tasks: validate.yml
  loop: "{{ disks }}"
  loop_control:
    loop_var: item

- name: "Сканирование системы (до выполнения)"
  include_tasks: scan_before.yml

- name: "Создание раздела (если указано)"
  include_tasks: create_partition.yml
  when: item.create_partition | default(false)
  loop: "{{ disks }}"
  loop_control:
    loop_var: item

- name: "Создание LVM (если указано)"
  include_tasks: create_lvm.yml
  when: item.use_lvm | default(false)
  loop: "{{ disks }}"
  loop_control:
    loop_var: item

- name: "Создание файловой системы"
  include_tasks: create_filesystem.yml
  loop: "{{ disks }}"
  loop_control:
    loop_var: item

- name: "Монтирование файловой системы"
  include_tasks: mount.yml
  loop: "{{ disks }}"
  loop_control:
    loop_var: item

- name: "Добавление записи в /etc/fstab"
  include_tasks: fstab.yml
  loop: "{{ disks }}"
  loop_control:
    loop_var: item

- name: "Проверка доступного пространства и результата (после)"
  include_tasks: scan_after.yml

- name: "Логирование"
  include_role:
    name: log-events
