- name: "Включение логики создания диска с нуля"
  ansible.builtin.include_tasks: create_logic.yml
  when: item.operation_type | default('create') == 'create'
  loop: "{{ disks }}"
  loop_control:
    loop_var: item

- name: "Включение логики расширения существующих LVM"
  ansible.builtin.include_tasks: extend_logic.yml
  when: item.operation_type == 'extend'
  loop: "{{ disks }}"
  loop_control:
    loop_var: item
