- name: "CREATE | Проверка критических точек монтирования"
  ansible.builtin.assert:
    that:
      - lv_item.mount_point not in ["/", "/boot", "/boot/efi", "/usr", "/etc", "/var", "/home", "/opt"]
    fail_msg: "Операция 'create': Точка монтирования {{ lv_item.mount_point }} запрещена."
  loop: "{{ item.lvs_to_create }}"
  loop_control: { loop_var: lv_item }
  when: "item.operation_type | default('create') == 'create'"

- name: "CREATE | Проверка, не используется ли уже устройство"
  ansible.builtin.shell: "mount | grep -q {{ item.device }}"
  register: device_check_create
  failed_when: device_check_create.rc == 0
  changed_when: false
  when: "item.operation_type | default('create') == 'create'"

- name: "EXTEND/STRETCH | Проверка критических точек монтирования"
  vars:
    forbidden_paths: ["/", "/boot", "/boot/efi", "/usr", "/etc", "/var", "/home", "/opt"]
  ansible.builtin.assert:
    that:
      - lv_item.mount_point not in forbidden_paths or (lv_item.allow_dangerous_resize | default(false)) # <-- ИЗМЕНЕНО
    fail_msg: "Попытка изменить критическую точку монтирования '{{ lv_item.mount_point }}' без флага подтверждения 'allow_dangerous_resize: true'." # <-- ИЗМЕНЕНО
  loop: "{{ item.lvs_to_modify }}"
  loop_control: { loop_var: lv_item }
  when: "item.operation_type == 'extend' or item.operation_type == 'stretch'"
