- name: "CREATE | Проверка критических точек монтирования"
  ansible.builtin.assert:
    that:
      - item.mount_point not in ["/", "/boot", "/boot/efi", "/usr", "/etc", "/var", "/home", "/opt"]
    fail_msg: "Операция 'create': Точка монтирования {{ item.mount_point }} запрещена."
  when: item.operation_type | default('create') == 'create'

- name: "CREATE | Проверка, не используется ли уже устройство"
  ansible.builtin.shell: "mount | grep -q {{ item.device }}"
  register: device_check_create
  failed_when: device_check_create.rc == 0
  changed_when: false
  when: item.operation_type | default('create') == 'create'


- name: "EXTEND | Проверка критических точек монтирования"
  vars:
    forbidden_paths: ["/", "/boot", "/boot/efi", "/usr", "/etc", "/var", "/home", "/opt"]
  ansible.builtin.assert:
    that:
      - lv_item.filesystem not in forbidden_paths or (lv_item.allow_dangerous_resize | default(false))
    fail_msg: "Попытка изменить критическую точку монтирования '{{ lv_item.filesystem }}' без флага подтверждения 'allow_dangerous_resize: true'."
  loop: "{{ item.lvs_to_modify }}"
  loop_control:
    loop_var: lv_item
  when: item.operation_type == 'extend'
