- name: Полная настройка серверов (Репозитории и Диски)
  hosts: all
  become: true
  
  pre_tasks:
    - name: Установить утилиты для работы с ФС (LVM, XFS)
      ansible.builtin.package:
        name:
          - lvm2
          - xfsprogs
        state: present

  vars:
    disk_configs_by_host:
      '10.96.34.145':
        - operation_type: extend
          disk_device: /dev/sdb
          vg_to_extend: debian-vg
          lvs_to_modify:
            - name: log_lv
              new_size: 50G
              filesystem: /var/log
              fs_type: ext4

      '10.96.34.146':
        - operation_type: extend
          disk_device: /dev/sdb
          vg_to_extend: debian-vg
          lvs_to_modify:
            - name: log_lv
              new_size: 20G
              filesystem: /var/log
              fs_type: ext4
            - name: data_lv
              new_size: 70G
              filesystem: /var/data
              fs_type: xfs

    disks: "{{ disk_configs_by_host[inventory_hostname] }}"

  roles:
    - role: infra/fix-repository
      fix_repository_exit_on_success: false
    - role: infra/manage-disks
