- name: Управление дисками (сценарий расширения LVM)
  hosts: all # Применяем ко всем хостам в инвентаре
  become: true
  
  # Здесь мы описываем, ЧТО мы хотим получить в итоге
  vars:
    disks:
      - # --- НАША ИНСТРУКЦИЯ ДЛЯ РОЛИ ---
        operation_type: extend      # Явно указываем, что будем РАСШИРЯТЬ существующую структуру

        disk_device: /dev/sdb     # Указываем НОВЫЙ ДИСК, который мы будем использовать для расширения
        vg_to_extend: debian-vg   # Говорим, какую СУЩЕСТВУЮЩУЮ группу томов нужно усилить

        lvs_to_modify:
          # В этом сценарии мы не меняем существующий /root, а только создаем новый том.
          # Если бы нужно было расширить и /root, мы бы добавили его сюда же.

          # Описываем новый том, который хотим СОЗДАТЬ в расширенной группе
          - name: log_lv          # Придумали имя для нового тома под логи
            new_size: 50G         # Выделим 50G из пространства нового диска
            filesystem: /var/log  # Указываем точку монтирования
            fs_type: ext4         # Указываем тип файловой системы для форматирования

  roles:
    - role: infra/manage-disks # Подключаем нашу роль
