- name: Создание пользователей с разными shell и sudo
  hosts: test_hosts
  become: true

  vars:
    users:
      - name: user_with_password
        manage_existing: true
        comment: "user_with_password_new"
        shell: /sbin/nologin
        groups: ["operator", "games"]
        sudo: no_password

      - name: user_no_login
        manage_existing: true
        shell: /bin/bash
        sudo: no_password

      - name: user_limited
        manage_existing: true
        shell: /bin/bash
        sudo: limited
        allowed_commands:
          - /usr/bin/systemctl restart sshd
          - /usr/bin/journalctl -u sshd
          - /usr/bin/systemctl restart cron.service

  roles:                 
    - infra/manage-users
