- name: Установка и обновление Node Exporter
  hosts: test_hosts
  become: true

  vars:
    update_node_exporter: false
    update_node_exporter_version: "" 

    node_exporter_state: "absent" 

    node_exporter_user: "node_exporter"
    node_exporter_group: "node_exporter"
    node_exporter_port: 9100

    node_exporter_groups:
      - name: "{{ node_exporter_group }}"
        system: false
        state: absent

    node_exporter_users:
      - name: "{{ node_exporter_user }}"
        group: "{{ node_exporter_group }}"
        system: true
        shell: /sbin/nologin
        create_home: false
        state: absent

    group_list: "{{ node_exporter_groups }}"
    users: "{{ node_exporter_users }}"

  roles:
    - monitoring/node-exporter 
    - infra/manage-users 
    - infra/manage-groups 
