- name: Клонирование ВМ через Proxmox API Token
  hosts: testing_cluster
  gather_facts: no
  connection: local
  vars_files:
    - ../inventory/testing/vault_proxmox-cloud-init-vm
    - ../inventory/testing/vault_ssh-pub-vm
    - ../inventory/testing/vm_list.yml
  roles:
    - role: infra/proxmox-cloud-init-vm

