#Вызывается как отдельная задача из роли /roles/infra/manage-user/
- name: Сброс пароля существующим пользователям
  hosts: all
  become: true

  vars_files:
    - ../inventory/testing/manage-users/user_list.yml

  tasks:
    - name: Сброс пароля
      include_role:
        name: infra/manage-users
        tasks_from: reset_password.yml
      loop: "{{ users }}"
      loop_control:
        loop_var: item
      when:
        - item.reset_password is defined
        - item.reset_password
