all:
  children:
    web:
      hosts:
        web01:
          ansible_host: 192.168.1.10
          ansible_user: ubuntu
    db:
      hosts:
        db01:
          ansible_host: 192.168.1.20
          ansible_user: postgres

